from vector_quantize.vector_quantize import VectorQuantize
from vector_quantize.residual_vq import ResidualVQ, GroupedResidualVQ
from vector_quantize.random_projection_quantizer import RandomProjectionQuantizer
from vector_quantize.finite_scalar_quantization import FSQ
from vector_quantize.lookup_free_quantization import LFQ
from vector_quantize.residual_lfq import ResidualLFQ, GroupedResidualLFQ
from vector_quantize.residual_fsq import ResidualFSQ, GroupedResidualFSQ
